CREATE DATABASE ComicsKursach
USE ComicsKursach;
CREATE TABLE USERSDATA(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(MAX),
SURNAME NVARCHAR(MAX),
GENDER NVARCHAR(MAX),
AGE NVARCHAR(MAX));
CREATE TABLE LOGINANDPASSWORD(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
LOGINS NVARCHAR(MAX),
PASSWORDS NVARCHAR(MAX),
USERTYPE NVARCHAR(MAX) DEFAULT('USER'), FOREIGN KEY (ID) REFERENCES USERSDATA(ID));
INSERT INTO USERSDATA(NAME,SURNAME,GENDER,AGE) VALUES ('ADMIN','ADMIN','MALE','0');
INSERT INTO LOGINANDPASSWORD(LOGINS,PASSWORDS,USERTYPE) VALUES ('ADMIN','-1470019936','ADMIN');
SELECT * from  LOGINANDPASSWORD  WHERE (lOGINS = '123');
DROP TABLE LOGINANDPASSWORD;
DROP TABLE USERSDATA;

DROP TABLE CATEGORY;
DROP TABLE COMICSCOVER; 
DROP TABLE IMAGESITEMS;
DROP TABLE COMICSCOVERITEM;

CREATE TABLE CATEGORY(
IDCATEGORY BIGINT IDENTITY(1,1) PRIMARY KEY,
CATEGORY NVARCHAR(255) UNIQUE);

CREATE TABLE COMICSCOVER(
IDCOMICSCOVER BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCATEGORY NVARCHAR(255),
COMICSCOVERWALPAPER NVARCHAR(MAX),
COMICSCOVERWALPAPERTOIESSIE NVARCHAR(MAX),
COMICSNAME NVARCHAR(MAX),  FOREIGN KEY (IDPARENTCATEGORY) REFERENCES CATEGORY(CATEGORY));

CREATE TABLE COMICSCOVERITEM(
IDCOMICSCOVERITEMS BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCOMICS BIGINT,
ISSIE NVARCHAR(255) UNIQUE, FOREIGN KEY (IDPARENTCOMICS) REFERENCES COMICSCOVER(IDCOMICSCOVER));

CREATE TABLE IMAGESITEMS(
IDGROUPS BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCOMICSITEM NVARCHAR(255),
COMICSWALPAPER NVARCHAR(MAX), FOREIGN KEY (IDPARENTCOMICSITEM) REFERENCES COMICSCOVERITEM(ISSIE));
