CREATE DATABASE ComicsKursach
USE ComicsKursach;

CREATE TABLE USERSDATA(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
NAME NVARCHAR(MAX),
SURNAME NVARCHAR(MAX),
GENDER NVARCHAR(MAX),
AGE NVARCHAR(MAX));

CREATE TABLE LOGINANDPASSWORD(
ID BIGINT IDENTITY(1,1) PRIMARY KEY,
LOGINS NVARCHAR(255) UNIQUE,
PASSWORDS NVARCHAR(MAX),
USERTYPE NVARCHAR(MAX) DEFAULT('USER'), FOREIGN KEY (ID) REFERENCES USERSDATA(ID));
INSERT INTO USERSDATA(NAME,SURNAME,GENDER,AGE) VALUES ('ADMIN','ADMIN','MALE','0');
INSERT INTO LOGINANDPASSWORD(LOGINS,PASSWORDS,USERTYPE) VALUES ('ADMIN','-1470019936','ADMIN');

CREATE TABLE USERIMAGE(
IDUSERIMAGE  BIGINT IDENTITY(1,1) PRIMARY KEY,
IDUSERNAME BIGINT UNIQUE, FOREIGN KEY (IDUSERNAME) REFERENCES LOGINANDPASSWORD(ID),
USERIMAGEPHOTO NVARCHAR(MAX));


DROP TABLE LOGINANDPASSWORD;
DROP TABLE USERSDATA;
DROP TABLE IMAGESITEMS;
DROP TABLE COMICSCOVERITEM;
DROP TABLE HISTORY;
DROP TABLE COMICSCOVER; 
DROP TABLE CATEGORY;
DROP TABLE FAVOURITES;
DROP TABLE USERIMAGE;
DROP TABLE COMICSCOMMENT;
drop table MARK;

CREATE TABLE CATEGORY(
IDCATEGORY BIGINT IDENTITY(1,1) PRIMARY KEY,
CATEGORY NVARCHAR(255) UNIQUE);
CREATE TABLE COMICSCOVER(
IDCOMICSCOVER BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCATEGORY NVARCHAR(255),
COMICSCOVERWALPAPER NVARCHAR(MAX),
COMICSCOVERWALPAPERTOIESSIE NVARCHAR(MAX),
COMICSDISCRIPTION NVARCHAR(MAX),
COMICSNAME NVARCHAR(255) UNIQUE,  FOREIGN KEY (IDPARENTCATEGORY) REFERENCES CATEGORY(CATEGORY));

CREATE TABLE HISTORY(
IDHISTORY BIGINT IDENTITY(1,1) PRIMARY KEY,
IDUSERLOGIN NVARCHAR(255),
IDHISTORYCOMICS NVARCHAR(255),
IDCOMICSCOVER BIGINT,
IDPARENTCATEGORY NVARCHAR(255),
COMICSCOVERWALPAPER NVARCHAR(MAX),
COMICSCOVERWALPAPERTOIESSIE NVARCHAR(MAX),
COMICSDISCRIPTION NVARCHAR(MAX));
CREATE TABLE FAVOURITES(
IDFAFOURITES BIGINT IDENTITY(1,1) PRIMARY KEY,
IDUSERLOGIN NVARCHAR(255),
IDFAFOURITECOMICS NVARCHAR(255),
IDCOMICSCOVER BIGINT,
IDPARENTCATEGORY NVARCHAR(255),
COMICSCOVERWALPAPER NVARCHAR(MAX),
COMICSCOVERWALPAPERTOIESSIE NVARCHAR(MAX),
COMICSDISCRIPTION NVARCHAR(MAX));
CREATE TABLE COMICSCOMMENT(
IDCOMICSCOMMENT BIGINT IDENTITY(1,1) PRIMARY KEY,
IDCOMICSCOVER  NVARCHAR(255),
USERNAME NVARCHAR(255),
COMMENTMESSAGE NVARCHAR(MAX));


CREATE TABLE COMICSCOVERITEM(
IDCOMICSCOVERITEMS BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCOMICS BIGINT,
ISSIE NVARCHAR(255) UNIQUE, FOREIGN KEY (IDPARENTCOMICS) REFERENCES COMICSCOVER(IDCOMICSCOVER));

CREATE TABLE IMAGESITEMS(
IDGROUPS BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCOMICSITEM NVARCHAR(255),
COMICSWALPAPER NVARCHAR(MAX), FOREIGN KEY (IDPARENTCOMICSITEM) REFERENCES COMICSCOVERITEM(ISSIE));

CREATE TABLE MARK(
IDMARK BIGINT IDENTITY(1,1) PRIMARY KEY,
IDPARENTCOMICS NVARCHAR(255),
IDNAMECOMICS NVARCHAR(255),
IDUSERNAME NVARCHAR(255),
STAR Float);

